default_platform(:ios)

platform :ios do

  desc "Build and upload to App Store"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true,
    )

    match(
      type: "appstore",
      app_identifier: "com.japinait.app",
      git_url: "https://#{ENV["GH_PAT"]}@github.com/jnaula/japinait-certificates.git",
      git_basic_authorization: Base64.strict_encode64("#{ENV["GH_PAT"]}:#{ENV["GH_PAT"]}"),
      keychain_password: ENV["MATCH_PASSWORD"],
      api_key: api_key,
      readonly: false
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/App/App.xcodeproj",
      team_id: ENV["APP_STORE_CONNECT_TEAM_ID"],
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore com.japinait.app",
      targets: ["App"]
    )

    build_app(
      scheme: "App",
      project: "ios/App/App.xcodeproj",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.japinait.app" => "match AppStore com.japinait.app"
        }
      }
    )

    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false
    )
  end
end